manifest = "dcd398354ea348c151602d732e3d505b470523b62142105385bf796bc4ac1e4e"

[[dependency]]
package = "github.com/buckaroo-pm/catch2"
target = "//:catch"

[[dependency]]
package = "github.com/buckaroo-pm/madler-zlib"
target = "//:zlib"

[[lock]]
name = "github.com/buckaroo-pm/catch2"
revision = "65ab25beb9080c77a7aa0edbfab1812a06e174d1"

[[lock]]
name = "github.com/buckaroo-pm/madler-zlib"
revision = "5869186a1ce0283cc1ee189f5771ef9cc3236c50"
